apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - elasticsearch-service.yaml
  - operate-service.yaml
  - zeebe-service.yaml
  - elasticsearch-deployment.yaml
  - zeebe-elasticsearch-data-persistentvolumeclaim.yaml
  - operate_zeebe_network-networkpolicy.yaml
  - operate-deployment.yaml
  - operate-claim0-persistentvolumeclaim.yaml
  - zeebe-deployment.yaml
  - zeebe-data-persistentvolumeclaim.yaml
  - zeebe-claim1-persistentvolumeclaim.yaml